<?php
return [
    'WA_BUSINESS_PHONE' => $_ENV['WA_BUSINESS_PHONE'] ?? getenv('WA_BUSINESS_PHONE') ?: '51979701851',
    'WA_DEFAULT_COUNTRY_CODE' => $_ENV['WA_DEFAULT_COUNTRY_CODE'] ?? getenv('WA_DEFAULT_COUNTRY_CODE') ?: '51',
];
